# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_status.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'event_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65vent_status.proto\x12\x0c\x65num_control*\xf0\x01\n\x0b\x45ventStatus\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n\x0eSTATUS_PENDING\x10\x01\x12\x11\n\rSTATUS_ACTIVE\x10\x02\x12\x14\n\x10STATUS_COMPLETED\x10\x03\x12\x11\n\rSTATUS_FAILED\x10\x04\x12\x12\n\x0eSTATUS_ABORTED\x10\x05\x12 \n\x1c\x45XAMPLE_EVENT_STATUS_STARTED\x10\x33\x12\"\n\x1e\x45XAMPLE_EVENT_STATUS_COMPLETED\x10\x34\x12\x1f\n\x1b\x45XAMPLE_EVENT_STATUS_FAILED\x10\x35*\x94\x02\n\tEventType\x12\x15\n\x11\x45VENT_UNSPECIFIED\x10\x00\x12\x11\n\rEVENT_GENERIC\x10\x01\x12\x0e\n\nEVENT_MAIN\x10\x02\x12\x1e\n\x1a\x45VENT_DATA_BASE_PROCESSING\x10\x03\x12\x15\n\x11\x45VENT_API_REQUEST\x10\x04\x12\x16\n\x12\x45VENT_API_RESPONSE\x10\x05\x12\x1d\n\x19\x45XAMPLE_EVENT_API_INVOKED\x10\x65\x12\x1e\n\x1a\x45XAMPLE_EVENT_API_RESPONSE\x10\x66\x12 \n\x1c\x45XAMPLE_EVENT_DATA_PROCESSED\x10h\x12\x1d\n\x19\x45XAMPLE_EVENT_DATA_STORED\x10ib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTSTATUS']._serialized_start=37
  _globals['_EVENTSTATUS']._serialized_end=277
  _globals['_EVENTTYPE']._serialized_start=280
  _globals['_EVENTTYPE']._serialized_end=556
# @@protoc_insertion_point(module_scope)
