LOGGING_BASE_DIR = "logs"
LOGGING_BACKUP_DIR = "history"
LOGGING_MAIN_FILE_NAME = "logs"
LOGGING_DEBUG_FILE_NAME = "debug_logs"
LOGGING_BACKUP_COUNT = 5
LOGGING_LOGGER_NAME = "MAIN"
LOGGING_FILE_SIZE = 1024
