import os
import re
import subprocess

"""
This script is used to generate the classes from the proto files.
The classes are generated in the parent directory of the current directory.

There is a bug in the classes generated by the protoc compiler when proto 
import other proto files, so this script also modifies the import statements 
in the generated classes to make them work.

Note 1: Make sure to run this script in the same directory as the proto files.
Note 2: Make sure to install protoc before running this script.
Note 3: This script needs to be executed every time a new proto file is added
or existing proto files are modified.
"""
files_list = list(filter(lambda filename: filename.endswith('.proto'), os.listdir('.')))
for filename in files_list:
    subprocess.run(["protoc", "--proto_path=.", "--python_out=../", filename])

classes_files_list = list(filter(lambda filename: filename.endswith('_pb2.py'), os.listdir('../')))
for filename in classes_files_list:
    try:
        with open(os.path.join('../', filename), 'r') as file:
            lines = file.readlines()
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        break

    import_string = r"import\s+\w+_pb2\sas\s\w+__\w+__pb2"
    with open(os.path.join('../', filename), 'w') as file:
        for line in lines:
            if re.search(import_string, line):
                file.write("from . " + line)
            else:
                file.write(line)
